(xbindkey '(Control Escape)                         "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Control+Escape\"")
(xbindkey '(Control Shift Alt Mod4 Mod5 Control_R)  "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Control+Shift+Alt+Mod4+Mod5+Control_R\"")
(xbindkey '(Control Shift Mod2 Mod4 Mod5 Control_R) "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Control+Shift+Mod2+Mod4+Mod5+Control_R\"")
(xbindkey '(Mod4 1)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+1\"")
(xbindkey '(Mod4 2)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+2\"")
(xbindkey '(Mod4 3)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+3\"")
(xbindkey '(Mod4 4)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+4\"")
(xbindkey '(Mod4 5)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+5\"")
(xbindkey '(Mod4 F1)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F1\"")
(xbindkey '(Mod4 F10)                               "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F10\"")
(xbindkey '(Mod4 F11)                               "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F11\"")
(xbindkey '(Mod4 F12)                               "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F12\"")
(xbindkey '(Mod4 F2)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F2\"")
(xbindkey '(Mod4 F3)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F3\"")
(xbindkey '(Mod4 F4)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F4\"")
(xbindkey '(Mod4 F5)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F5\"")
(xbindkey '(Mod4 F6)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F6\"")
(xbindkey '(Mod4 F7)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F7\"")
(xbindkey '(Mod4 F9)                                "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+F9\"")
(xbindkey '(Mod4 a)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+a\"")
(xbindkey '(Mod4 c)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+c\"")
(xbindkey '(Mod4 d)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+d\"")
(xbindkey '(Mod4 e)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+e\"")
(xbindkey '(Mod4 equal)                             "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+equal\"")
(xbindkey '(Mod4 f)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+f\"")
(xbindkey '(Mod4 m)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+m\"")
(xbindkey '(Mod4 n)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+n\"")
(xbindkey '(Mod4 r)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+r\"")
(xbindkey '(Mod4 s)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+s\"")
(xbindkey '(Mod4 shift A)                           "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+shift+A\"")
(xbindkey '(Mod4 t)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+t\"")
(xbindkey '(Mod4 w)                                 "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"Mod4+w\"")
(xbindkey '(XF86Calculator)                         "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86Calculator\"")
(xbindkey '(XF86HomePage)                           "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86HomePage\"")
(xbindkey '(XF86Mail)                               "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86Mail\"")
(xbindkey '(XF86ScreenSaver)                        "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86ScreenSaver\"")
(xbindkey '(XF86Search)                             "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86Search\"")
(xbindkey '(XF86Tools)                              "/usr/lib/kamilscripts/bin/,X11_shortcuts.sh \"XF86Tools\"")

