#!/bin/bash

build() {
    map add_binary \
        tar \
        gzip
    add_runscript
}

help() {
    cat<<HELPEOF
This hooks allows copying whole chroot to tmppfs and boot from it.

Command Line Setup:

    Set root=.. to a block device containing chroot.
    Set memchroot=... to a directory or file with chroot.
    This hook will copy whole chroot structure to tmpfs mounted directory.
    Then the boot process will continue, with rootfs mounted to tmpfs.
    Omiting memchroot=... parameter allows booting as usual, from root=... device.
    This hook also adds binaries tar and gzip to image.

    Supported memchroot parameters:
        - directory   
            memchroot=/root/debianchroot
        - .tar archive file
            memchroot=/root/debianchroot.tar
        - .tar.gz archive file
            memchroot=/root/debianchroot.tar.gz
        - .tar.bz2 archive file ( you need to add bzip2 binary to image )
            memchroot=/root/debianchroot.tar.bz2
    
Examples:

        root=/dev/sda1 memchroot=/home/users/bob/debianchroot

        root=UUID=aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee memchroot=/

        root=/dev/sda1 memchroot=/root/ubuntuarchive.tar.gz

HELPEOF
}

# vim: set ts=4 sw=4 ft=sh et:
