#!/bin/bash

build() {
	if ! hash memtester; then
		echo "ERROR - you must install memtester package first!"
		echo "yaourt -S --noconfirm memtester"
		exit 1
	fi

	map add_binary \
		beep sed ifconfig dhcpcd w3m ssh watch uptime sleep bash sh seq \
		su awk cat sleep echo killall memtester ps sensors bash openvt \
		htop lsusb hostname mesg ls ip cut date top dmesg watch \
		ssh-keygen touch chgrp chmod sensors-detect who whoami getent \
		tty ethtool

    add_file "/usr/lib/initcpio/qqmemtestertestscript" "/usr/local/bin/qqmemtestertestscript"

    add_runscript

    for i in /etc/bash.bashrc /usr/lib/terminfo/l/linux /usr/share/terminfo/x/xterm /etc/sensors3.conf; do
    	add_file "$i" "$i"
    done
}

help() {
    cat <<HELPEOF
This hooks allows to run memtester extensive testing on boot if set.

Command line options:
	This hook activates if memtester=y is set.
	Omiting setting memtester=... will result in normal booting.

Example:

		memtester=y

HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
