#!/bin/bash

build() {
	map add_binary \
		beep sed ifconfig dhcpcd w3m ssh watch uptime sleep bash sh seq \
		su awk cat sleep echo killall ps sensors bash openvt \
		htop lsusb hostname mesg ls ip cut date top dmesg watch \
		ssh-keygen touch chgrp chmod sensors-detect who whoami getent \
		tty ethtool mprime

    add_file "/usr/lib/initcpio/qqstresserscript" "/usr/local/bin/qqstresserscript"

    add_runscript

    for i in /etc/bash.bashrc /usr/lib/terminfo/l/linux /usr/share/terminfo/x/xterm /etc/sensors3.conf /usr/lib/dhcpcd/dhcpcd-hooks/20-resolv.conf /usr/lib/dhcpcd/dhcpcd-hooks/30-hostname /usr/lib/dhcpcd/dhcpcd-run-hooks; do
    	add_file "$i" "$i"
    done
}

help() {
    cat <<HELPEOF
This hooks allows to run mprime extensive testing on boot if set.

Command line options:
	This hook activates if stresser=y is set.
	Omiting setting stresser=... will result in normal booting.

Example:

		stresser=y

HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
