
image: archlinux/base
variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

.test_setup: &test_setup
  before_script:
    - pacman -Suy --noconfirm tar python awk grep gettext make diffutils bc 
    - echo "$BASH_VERSION" || true
    - export "PATH=$PWD/bin:$PATH"

test_stow:
  <<: *test_setup
  script:
    - mkdir -p /tmp/stow
    - bin/,install_stow.sh /tmp/stow
    - /tmp/stow/stow --version
test_proot:
  <<: *test_setup
  script:
    - bin/,proot --version
test_alias_complete:
  <<: *test_setup
  script:
    - bin/alias_complete.sh --unittest
test_blockinfile:
  <<: *test_setup
  script:
    - bin/blockinfile.sh --unittest
test_,hextodectobin:
  <<: *test_setup
  script:
    - bin/,hextodectobin --test
test_bash_autotranslate:
  <<: *test_setup
  script:
    - echo pl_PL.UTF-8 UTF-8 >> /etc/locale.gen
    - sed -i -e 's/NoExtract/#NoExtract/' /etc/pacman.conf
    - pacman -S --noconfirm glibc
    - bin/,bash_autotranslate.sh --test
test_lineinfile:
  <<: *test_setup
  script:
    - bin/lineinfile.sh --unittest
test_ccrun:
  <<: *test_setup
  script:
    - pacman -Suy --noconfirm gcc
    - bin/,ccrun ---test

pages:
  stage: deploy
  only:
    - master
  script:
    - pkg/archlinux/docker_build.sh ./archlinux-output
    - pkg/archlinux/repo_create.sh ./public/archlinux/kamilrepo ./archlinux-output
    - pkg/create_index.sh ./public/
  artifacts:
    paths:
      - public

