
stages:
- build

variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

build:
  stage: build
  image: archlinux/base
  script:
  - pkg/archlinux/docker_build.sh ./output
  - pkg/create_index.sh ./public/index.html
  - pkg/archlinux/repo_create.sh ./public/archlinux/kamilscripts
  
