variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

pages:
  stage: build
  image: archlinux/base
  only:
    - master
  script:
  - mkdir -p /tmp/stow && bin/,install_stow.sh /tmp/stow && /tmp/stow/stow --version
  - pkg/archlinux/docker_build.sh ./archlinux-output
  - pkg/archlinux/repo_create.sh ./public/archlinux/kamilrepo ./archlinux-output
  - pkg/create_index.sh ./public/
  artifacts:
    paths:
      - public

