
variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"
archbuild:
  image: base/archlinux
  script:
  - pacman -Sy --needed --noconfirm base-devel git
  - cd pkg-archlinux
  - chown -R nobody:nobody .
  - sudo -u nobody makepkg
  - cd ..
  - mkdir output
  - mv -v pkg-archlinux/*.pkg.tar.xz output
  artifacts:
    paths:
    - output

