
stages:
- build
- deploy

variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

build:
  stage: build
  image: archlinux/base
  script:
  - pkg/archlinux/docker_build.sh ./output
  artifacts:
    paths:
    - ./output/*

deploy:
  stage: deploy
  image: busybox
  script:
  - wget --post-data='' "https://gitlab.com/api/v4/projects/7024812/trigger/pipeline?token=$archlinux_repo_trigger&ref=master"
  only:
  - tags
  - master
  
