
variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

pages:
  stage: build
  image: antergos/makepkg
    #archlinux/base
  script:
  - pkg/archlinux/docker_build.sh ./archlinux-output
  - pkg/archlinux/repo_create.sh ./public/archlinux/kamilrepo ./archlinux-output
  - pkg/create_index.sh ./public/
  artifacts:
    paths:
      - public

