
variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"
archbuild:
  image: base/archlinux
  script:
  - pacman -Sy --needed --noconfirm base-devel git
  - cd pkg-archlinux
  - chown -R nobody:nobody .
  - sudo -u nobody makepkg
  - mkdir -p ../output
  - mv -v *.pkg.tar.xz ../output
#  artifacts:
#    paths:
#    - output

deploy:
  image: busybox
  script:
  - wget --post-data="token=$archlinux_repo_trigger" https://gitlab.com/api/v4/projects/7024812/trigger/pipeline&ref=master

