---
build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --force --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE:latest

image: $CI_REGISTRY_IMAGE:latest
variables:
  PACKAGER: "Kamil Cukrowski <kamilcukrowski@gmail.com> via gitlab"

.test_setup: &test_setup
  before_script:
    - export "PATH=$PWD/bin:$PATH"

shellcheck:
  image: koalaman/shellcheck-alpine:stable
  allow_failure: true
  stage: test
  script:
    - shellcheck --version
    - find . -type f '(' -iname '*.sh' -o -iname '*.bash' ')' -print0 > /tmp/files
    - xargs -0t shellcheck -x < /tmp/files

test_docker-rsync-volumes:
  <<: *test_setup
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_VERIFY: 1
    DOCKER_CERT_PATH: "$DOCKER_TLS_CERTDIR/client"
  script:
    - pacman -S --noconfirm docker
    - bin/,docker-rsync-volumes --test

test_install_stow:
  <<: *test_setup
  script:
    - bin/,install_stow.sh --unittest
test_proot:
  <<: *test_setup
  script:
    - bin/,proot --version
test_alias_complete:
  <<: *test_setup
  script:
    - bin/alias_complete.sh --unittest
test_blockinfile:
  <<: *test_setup
  script:
    - bin/blockinfile.sh --unittest
test_,hextodectobin:
  <<: *test_setup
  script:
    - bin/,hextodectobin --test
test_bash_autotranslate:
  <<: *test_setup
  script:
    - echo pl_PL.UTF-8 UTF-8 >> /etc/locale.gen
    - sed -i -e 's/NoExtract/#NoExtract/' /etc/pacman.conf
    - pacman -S --noconfirm glibc
    - bin/,bash_autotranslate.sh --test
test_lineinfile:
  <<: *test_setup
  script:
    - bin/lineinfile.sh --unittest
test_ccrun:
  <<: *test_setup
  script:
    - pacman -Suy --noconfirm gcc
    - bin/,ccrun +unittest
test_rstow:
  <<: *test_setup
  script:
    - bin/,rstow unittest
test_fnmatch:
  <<: *test_setup
  script:
    - bin/,fnmatch --test
test_lib_lib:
  <<: *test_setup
  script:
    - bin/,lib_lib --test

pages:
  stage: deploy
  only:
    - master
  script:
    - pkg/archlinux/docker_build.sh ./archlinux-output
    - pkg/archlinux/repo_create.sh ./public/archlinux/kamilrepo ./archlinux-output
    - pkg/create_index.sh ./public/
  artifacts:
    paths:
      - public
