#!/bin/bash
# https://click.palletsprojects.com/en/8.1.x/shell-completion/
eval "$(
	# Take name and uppercase complete it with variable.
	name="${BASH_SOURCE[0]##*/}"
	env "_${name^^}_COMPLETE=bash_source" "$name"
)"
