[font]
size = 11.0
[font.normal]
family = 'LiterationMono Nerd Font'

[colors.primary]
background = '#000000'
foreground = '#ffffff'
[colors.cursor]
cursor = '#ffffff'
text   = '#000000'
[colors.normal]
black   = '#181818'
red     = '#b21818'
green   = '#18b218'
yellow  = '#b26818'
blue    = '#3737ff'
magenta = '#b218b2'
cyan    = '#18b2b2'
white   = '#b2b2b2'
[colors.bright]
black   = '#686868'
red     = '#ff5454'
green   = '#54ff54'
yellow  = '#ffff54'
blue    = '#5454ff'
magenta = '#ff54ff'
cyan    = '#54ffff'
white   = '#ffffff'
[colors.selection]
background = '#4e5a65'
text       = '#d8dee9'

[selection]
save_to_clipboard = true
