#!/bin/sh
# kamilscripts etc/profile

if [ -r "${KCDIR:-}" ]; then
	return;
fi

# find KCDIR
for i in \
		/usr/lib/kamilscripts \
		"$HOME"/.kamilscripts \
		"$HOME"/.config/kamilscripts/kamilscripts \
		"$HOME"/.config/kamilscripts \
; do
	if [ -e "$i" ] && [ -e "$i"/.git ] && [ -e "$i"/bin ]; then
		KCDIR=$(readlink -f "$i")
		break
	fi
done
unset i

if [ -z "$KCDIR" ]; then
	echo "KCDIR not found" >&2
	return
fi

##################

for _i in "$KCDIR"/etc/profile.d/*.sh; do
	if [ -r "$_i" ]; then
		. "$_i"
	fi
done
unset _i

