#!/bin/sh
# kamilscripts etc/profile

for _i in \
		"${XDG_CONFIG_HOME:-~/.config}"/profile.d/*.sh \
		~/.profile_*
do
	if [ -e "$_i" ]; then
		# shellcheck disable=SC1090
		. "$_i"
	fi
done
unset _i

if [ -r "${KCDIR:-}" ]; then
	return;
fi

# find KCDIR
_i=~/.kamilscripts
if [ -r "$_i" ] && [ -r "$_i"/.git ] && [ -r "$_i"/bin ]; then
	KCDIR=$(readlink -f "$_i")
else
	echo ".kamilscripts/etc/profile: KCDIR not found" >&2
	return
fi
unset _i

export KCDIR

for _i in "$KCDIR"/etc/profile.d/*.sh; do
	if [ -r "$_i" ]; then
		# shellcheck disable=SC1090
		. "$_i"
	fi
done
unset _i

