#!/bin/sh

for i in \
catonlines.sh \
gtitsbackup.sh

do
	tmp=$(
		"$i" -h |
		grep '^[[:space:]]' |
		tr '[:space:]' '\n' |
		grep  '^-' |
		cut -d= -f1 |
		sed 's/,$// ; /^-$/d' |
		tr '\n' ' ' |
		sort -u
	)
	complete -W "$tmp" "$i"
done
