#!/bin/bash
# Kamil Cukrowski 
# /etc/rc-local folder is referenced by systemd services:
# rc-local-run-parts-boot.service and rc-local-run-parts-shutdown.service
# On boot the rc-local-run-parts-boot.service will run all executables 
#   in /etc/rc-local/ directory and pass one argument 'boot' to them.
# On shutdown rc-local-run-parts-shutdown.service will run all executables
#   in /etc/rc-local/ directory and pass one argument 'shutdown' to them.
case "$1" in
boot)
	;;
shutdown)
	;;
esac

