#!/bin/bash -e
test "$ENCRYPTFILTERDEBUG" = 'true' && set -x
. .gitencrypt/password "$@"
mode=$1
file=$2
case "$mode" in
clean)
	clean "$file"
	;;
diff)
	diff "$file" 2>/dev/null || cat "$file"
	;;
smudge)
	smudge "$file" 2>/dev/null || cat
	;;
*)
	echo "ERROR - bad encryptfilter mode - $mode" 1>&2
	exit 1
	;;
esac



