#!/bin/bash
# Kamil Cukrowski
# under beerware license

memchroot_mount_handler () {
   local tempmnt="/temp_root"
   local localmemchroot="${tempmnt}/${memchroot}"

   if [ ! -b "$root" ]; then
      err  "Unable to find root device '$root'."
      echo "You are being dropped to a recovery shell"
      echo "    Type 'exit' to try and continue booting"
      launch_interactive_shell
      msg "Trying to continue (this will most likely fail) ..."
   fi

   msg ":: mounting '$root' on temp root"
   if ! mkdir "${tempmnt}"; then
      echo "Could not create temp mount directory."
      launch_interactive_shell
   fi
   if ! mount ${rootfstype:+-t $rootfstype} -o ro "$root" "${tempmnt}"; then
      echo "You are now being dropped into an emergency shell."
      launch_interactive_shell
      msg "Trying to continue (this will most likely fail) ..."
   fi
   msg "Mounted '$root' on temp root"

   mount -t tmpfs -o size=100% none ${1}
   if   [ -d "${localmemchroot}" ]; then
      msg "Found chroot under ${memrootfs} directory."
      msg "Copying directory to root."
      cp -rfa "${localmemchroot}"/* ${1} 
   elif [ -f "${localmemchroot}" ]; then
      msg "Found chroot in ${memchroot} file."
      local ext="${memchroot}"
      ext="${ext#*.}"
      case "${ext}" in
      tar)
         msg "Unpacking chroot from ${memchroot} tar archive file."
         tar -xf  "${localmemchroot}" -C "${1}"
         ;;
      tar.gz)
         msg "Unpacking chroot from ${memchroot} gzip+tar archive file."
         tar -zxf "${localmemchroot}" -C "${1}"
         ;;
      tar.bz2)
         msg "Unpacking chroot from ${memchroot} bzip2+tar archive file."
         tar -jxf "${localmemchroot}" -C "${1}"
	 ;;
      *)
         msg "Unknown ${memchroot} extension \"${ext}\". No idea how to parse it."
         msg "Leaving filesystem mounted readonly in ${tempmnt}"
         echo "You are now being dropped into an emergency shell."
         launch_interactive_shell
         ;;
      esac
   else
      msg "bad memchroot = ${memchroot}"
      msg "Leaving filesystem mounted readonly in ${tempmnt}"
      echo "You are now being dropped into an emergency shell."
      launch_interactive_shell
   fi
   umount ${tempmnt}
}

run_hook() {
   if [ -n "${memchroot}" ]; then
      mount_handler="memchroot_mount_handler"
   fi
}


# vim:set ts=4 sw=4 ft=sh et:
