#!/bin/bash
# Kamil Cukrowski
# under beerware license

memtester_mount_handler () {
   # this is not really a mount handler. it's init script
   exec /usr/local/bin/qqmemtestertestscript init
}

run_hook() {
   if [ -n "${memtester}" ]; then
      mount_handler="memtester_mount_handler"
   fi
}


# vim:set ts=4 sw=4 ft=sh et: